### ISSUE TITLE
How does rides available work?

### ISSUE THREAD

**Issue by rachelroks9** [David-Sparky/TakeMeHomeTonight#14]

**Comment by minars** [comment]
It makes a request to the backend, which then requests all of the data from the "offered" collection. This is then displayed on the front end using angular.

**Comment by minars** [comment]
The page generates a list based off of the data from the back-end. The list that is shown contains useful information regarding the ride such as where it is going and when it is leaving. Each item is clickable and will open a page with more detailed information. At this point the user is able to request to join the ride. The request will need to be accepted or denied by the owner of the ride. Once all available seats have been filled then the list item is no longer shown.
