### ISSUE TITLE
How does rides needed work?

### ISSUE THREAD

**Issue by rachelroks9** [David-Sparky/TakeMeHomeTonight#15]

**Comment by minars** [comment]
This works very similar to the rides offered page save for the fact that it pulls the data from the "requested" collection. The rides needed page displays a list of rides that people have requested. This list can be sorted by a number of meaning full values such as departure time and date, and more. Each item can be clicked on and will open to a page where the user can request to be the driver. Once a driver is accepted then the list item is no longer shown.
