### ISSUE TITLE
How does pending / attending work?

### ISSUE THREAD

**Issue by rachelroks9** [David-Sparky/TakeMeHomeTonight#21]

**Comment by minars** [comment]
Pending and attending/accepted work by using an array within the collection entry. This array is a list of RCS and Status. If the status is pending then they are pending being accepted. If the status is accepted then the user is accepted. When a user is rejected or removed then are are taken out of this array and therefore no longer pending/accepted. This array is the same for both ride offers and rides needed.

**Comment by minars** [comment]
Users can be accepted/rejected from within the ride page itself or from within their profile.

**Comment by minars** [comment]
Users can be accepted/rejected from within the ride page itself or from within their profile.

**Comment by minars** [comment]
Users can be accepted/rejected from within the ride page itself or from within their profile.
