### ISSUE TITLE
How does backend routing work?

### ISSUE THREAD

**Issue by rachelroks9** [David-Sparky/TakeMeHomeTonight#25]

**Comment by cmrenus** [comment]
Backend routing is split up among multiple files. We utilize express.static() to serve any static files and the index.html page is served up through a separate file which just sends the page. Any GET, PUT, DELETE, or POST requests pertaining to users and the '/users/' route, go through users.js route and anything for '/rides/' goes to rides.js. Login and logout are currently in the main server.js as well as the socket setup for notifications.
