### ISSUE TITLE
How does the one page, multiple views work?

### ISSUE THREAD

**Issue by rachelroks9** [David-Sparky/TakeMeHomeTonight#26]

**Comment by cmrenus** [comment]
The page first loads up the index page which uses the angular app, tmht in app.js, which is the app for the whole page. Within the app we set the initial configuration which includes using $routeProvider. Within routeProvider, we have the ability to change the view and controller as well as other things based upon the route. This way based on different routes, we can swap views in and out of the page, allowing for a single page application.
