### ISSUE TITLE
How does notifications work?

### ISSUE THREAD

**Issue by rachelroks9** [David-Sparky/TakeMeHomeTonight#34]

**Comment by cmrenus** [comment]
When clicking the bell in the corner a user can view the notifications that they have. When they have notifications they have not seen, a red bubble will show up on it showing them that they have unread notifications. When they click on it, the notifications are read and the bubble goes away. From here, they can click on a notification which will bring them to the ride in which that notification pertains to. The background color of the notification changes as well if they have not seen it yet. 

Technical standpoint
The notifications service utilizes sockets. This is done to provide live changes of notifications. Any time a change is made to a ride, whether it is a deletion of user or ride, or confirmation of a rider or driver, a notification is made to related users. The notification is pushed to a notification array that is per user. The object pushed contains the message, the date, whether it has been seen, the ride id it pertains to, and then whether it was an offered ride or requested. From here, the front end knows a change was made and send "update notifications" to the socket to request the notifications and the changes that have been made. Using rooms, created with a users rcs, the sockets are able to distinguish which socket is which and who to send the notifications to.
